sudo: false

language: node_js

node_js:
  - '0.12'

cache:
  directories:
    - app/bower_components
    - node_modules

branches:
  only:
    - /.*/ # all branches an gh-pages too

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install
  - npm install -g grunt-cli

script:
  - grunt tslint
  - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
