sudo: false

language: node_js

node_js:
  - '0.12'

cache:
  directories:
    - node_modules

branches:
  only:
    - gh-pages

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
