sudo: false

language: node_js

node_js:
  - '0.12'

cache:
  directories:
    - app/bower_components
    - node_modules

branches:
  only:
    - gh-pages

script:
  - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
